# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1011, 691))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_operate = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_operate.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_operate.setObjectName("gridLayout_operate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuOperate = QtWidgets.QMenu(self.menubar)
        self.menuOperate.setObjectName("menuOperate")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLincence = QtWidgets.QAction(MainWindow)
        self.actionLincence.setObjectName("actionLincence")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionChange_IC_Writer_Password = QtWidgets.QAction(MainWindow)
        self.actionChange_IC_Writer_Password.setObjectName("actionChange_IC_Writer_Password")
        self.actionChange_COM_Port = QtWidgets.QAction(MainWindow)
        self.actionChange_COM_Port.setObjectName("actionChange_COM_Port")
        self.actionIC_Sector = QtWidgets.QAction(MainWindow)
        self.actionIC_Sector.setObjectName("actionIC_Sector")
        self.actionProduct_Description = QtWidgets.QAction(MainWindow)
        self.actionProduct_Description.setObjectName("actionProduct_Description")
        self.actionWriting_Description = QtWidgets.QAction(MainWindow)
        self.actionWriting_Description.setObjectName("actionWriting_Description")
        self.actionManagement_Card = QtWidgets.QAction(MainWindow)
        self.actionManagement_Card.setObjectName("actionManagement_Card")
        self.actionUser_Card = QtWidgets.QAction(MainWindow)
        self.actionUser_Card.setObjectName("actionUser_Card")
        self.actionCard_Total = QtWidgets.QAction(MainWindow)
        self.actionCard_Total.setObjectName("actionCard_Total")
        self.actionSetting_Interface = QtWidgets.QAction(MainWindow)
        self.actionSetting_Interface.setObjectName("actionSetting_Interface")
        self.menuFile.addAction(self.actionLincence)
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionSetting_Interface)
        self.menuOperate.addAction(self.actionManagement_Card)
        self.menuOperate.addAction(self.actionUser_Card)
        self.menuOperate.addAction(self.actionCard_Total)
        self.menuHelp.addAction(self.actionProduct_Description)
        self.menuHelp.addAction(self.actionWriting_Description)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuOperate.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JMFK Card Management"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Settings"))
        self.menuOperate.setTitle(_translate("MainWindow", "Operate"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLincence.setText(_translate("MainWindow", "License Management"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionChange_IC_Writer_Password.setText(_translate("MainWindow", "Setting Interface"))
        self.actionChange_COM_Port.setText(_translate("MainWindow", "COM Port"))
        self.actionIC_Sector.setText(_translate("MainWindow", "IC Sector"))
        self.actionProduct_Description.setText(_translate("MainWindow", "Product Description"))
        self.actionWriting_Description.setText(_translate("MainWindow", "Write Card Description"))
        self.actionManagement_Card.setText(_translate("MainWindow", "Management Card"))
        self.actionUser_Card.setText(_translate("MainWindow", "User Card"))
        self.actionCard_Total.setText(_translate("MainWindow", "Card Total"))
        self.actionSetting_Interface.setText(_translate("MainWindow", "Setting Interface"))

