# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_User.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_User(object):
    def setupUi(self, User):
        User.setObjectName("User")
        User.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(User)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 971, 131))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 141, 91))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 55, 54, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(60, 20, 71, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 21))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(60, 55, 71, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(160, 20, 151, 91))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setGeometry(QtCore.QRect(60, 50, 81, 31))
        self.textEdit.setObjectName("textEdit")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 55, 54, 21))
        self.label_3.setObjectName("label_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 20, 531, 91))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 25, 91, 16))
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit.setGeometry(QtCore.QRect(90, 20, 111, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_5.setObjectName("label_5")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_2.setGeometry(QtCore.QRect(90, 55, 111, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(210, 25, 81, 16))
        self.label_6.setObjectName("label_6")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit.setGeometry(QtCore.QRect(290, 20, 71, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(210, 60, 81, 16))
        self.label_7.setObjectName("label_7")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit_2.setGeometry(QtCore.QRect(290, 55, 71, 22))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit_5.setGeometry(QtCore.QRect(370, 55, 71, 22))
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.timeEdit_6 = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit_6.setGeometry(QtCore.QRect(370, 20, 71, 22))
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.timeEdit_7 = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit_7.setGeometry(QtCore.QRect(450, 55, 71, 22))
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.timeEdit_8 = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit_8.setGeometry(QtCore.QRect(450, 20, 71, 22))
        self.timeEdit_8.setObjectName("timeEdit_8")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(870, 40, 101, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(860, 70, 101, 34))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 971, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_65 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_65.setGeometry(QtCore.QRect(20, 270, 71, 21))
        self.checkBox_65.setObjectName("checkBox_65")
        self.checkBox_66 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_66.setGeometry(QtCore.QRect(110, 270, 71, 21))
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_67 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_67.setGeometry(QtCore.QRect(200, 270, 71, 21))
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_68 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_68.setGeometry(QtCore.QRect(290, 270, 71, 21))
        self.checkBox_68.setObjectName("checkBox_68")
        self.checkBox_69 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_69.setGeometry(QtCore.QRect(380, 270, 71, 21))
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_70 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_70.setGeometry(QtCore.QRect(470, 270, 71, 21))
        self.checkBox_70.setObjectName("checkBox_70")
        self.checkBox_71 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_71.setGeometry(QtCore.QRect(560, 270, 71, 21))
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkBox_72 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_72.setGeometry(QtCore.QRect(650, 270, 71, 21))
        self.checkBox_72.setObjectName("checkBox_72")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 0, 971, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(80, 30, 171, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(250, 30, 81, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(320, 30, 101, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(470, 30, 81, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(520, 30, 181, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(700, 30, 101, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(800, 30, 111, 31))
        self.label_22.setObjectName("label_22")
        User.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(User)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 30))
        self.menubar.setObjectName("menubar")
        User.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(User)
        self.statusbar.setObjectName("statusbar")
        User.setStatusBar(self.statusbar)

        self.retranslateUi(User)
        QtCore.QMetaObject.connectSlotsByName(User)

    def retranslateUi(self, User):
        _translate = QtCore.QCoreApplication.translate
        User.setWindowTitle(_translate("User", "Usercard"))
        self.groupBox.setTitle(_translate("User", "选择功能"))
        self.label_2.setText(_translate("User", "群号："))
        self.label.setText(_translate("User", "群号："))
        self.checkBox_2.setText(_translate("User", "使用计数功能"))
        self.label_3.setText(_translate("User", "次数："))
        self.label_4.setText(_translate("User", "开始日期："))
        self.label_5.setText(_translate("User", "结束日期："))
        self.label_6.setText(_translate("User", "开始时间："))
        self.label_7.setText(_translate("User", "结束时间："))
        self.checkBox.setText(_translate("User", "开关卡"))
        self.pushButton.setText(_translate("User", "写卡"))
        self.groupBox_2.setTitle(_translate("User", "写入控制数据"))
        self.checkBox_65.setText(_translate("User", "列选"))
        self.checkBox_66.setText(_translate("User", "列选"))
        self.checkBox_67.setText(_translate("User", "列选"))
        self.checkBox_68.setText(_translate("User", "列选"))
        self.checkBox_69.setText(_translate("User", "列选"))
        self.checkBox_70.setText(_translate("User", "列选"))
        self.checkBox_71.setText(_translate("User", "列选"))
        self.checkBox_72.setText(_translate("User", "列选"))
        self.groupBox_6.setTitle(_translate("User", "IC卡信息"))
        self.label_15.setText(_translate("User", "序列号："))
        self.label_16.setText(_translate("User", "TextLabel"))
        self.label_17.setText(_translate("User", "用户名："))
        self.label_18.setText(_translate("User", "TextLabel"))
        self.label_19.setText(_translate("User", "公司："))
        self.label_20.setText(_translate("User", "TextLabel"))
        self.label_21.setText(_translate("User", "卡片状态："))
        self.label_22.setText(_translate("User", "TextLabel"))

